### ISSUE TITLE
WLED output pin?

### ISSUE THREAD

**Issue by numindast** [Planet-Laterna/Laterna-mini#2]
Hello - without thinking, I flashed WLED onto my new Mini instead of using the pre-flashed one. My newly flashed WLED GUI works but I'm not getting any output. What should the output pin be for the strip? Thx!

**Comment by monoapp3** [comment]
hi, if you are using Laterna mini V1 please refer to 
https://github.com/Planet-Laterna/Laterna-mini#pinout-description, you will find relevant pins described

if you are using Laterna mini V3, please configure GPIO 27. Diagram will be updated under 

https://github.com/Planet-Laterna/Laterna-mini-V3

**Comment by numindast** [comment]
Thank you so much - the v3 is what I have and I have light!
